# Generated by Django 3.2.5 on 2022-02-01 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 13, 58, 16, 270547, tzinfo=utc), verbose_name='date published'),
        ),
    ]
